# Generated by Django 3.0.8 on 2020-07-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0004_testpy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
