# Generated by Django 3.0.8 on 2020-07-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0005_delete_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('airtable_record_id', models.CharField(blank=True, db_index=True, max_length=35)),
                ('name', models.CharField(max_length=200)),
                ('total_awesomeness', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'verbose_name': 'The Best HomePage Ever',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.DeleteModel(
            name='TestPy',
        ),
    ]
