# Generated by Django 3.0.8 on 2020-07-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200706_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Test_py'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='total_awesomeness',
        ),
    ]
