# Generated by Django 3.0.8 on 2020-07-06 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPy',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('airtable_record_id', models.CharField(blank=True, db_index=True, max_length=35)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Test_py',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
