# Generated by Django 3.0.8 on 2020-07-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_py', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpy',
            options={'verbose_name': 'Baha'},
        ),
    ]
